name: Publish Docker image
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    tags:
    - 'v*'
jobs:
  build_amd64:
    name: Build amd64 docker image
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Get Version
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build and push (development)
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ci/Dockerfile
          tags: luxonis/depthai-library:${{github.sha}}-amd64
      - name: Build and push (release)
        if: startsWith(github.ref, 'refs/tags/v') == true
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ci/Dockerfile
          tags: luxonis/depthai-library:${{ steps.vars.outputs.short_ref }}-amd64

  build_armv7:
    name: Build armv7 docker image
    runs-on: luxonis-armhf
    timeout-minutes: 240
    steps:
      - name: Clean the workspace
        uses: docker://alpine
        with:
          args: /bin/sh -c "rm -rf /github/workspace/.* || rm -rf /github/workspace/*"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Get Version
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build and push (development)
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ci/Dockerfile
          tags: luxonis/depthai-library:${{github.sha}}-armv7
      - name: Build and push (release)
        if: startsWith(github.ref, 'refs/tags/v') == true
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ci/Dockerfile
          tags: luxonis/depthai-library:${{ steps.vars.outputs.short_ref }}-armv7

  build_armv8:
    name: Build armv8 docker image
    runs-on: ARM64
    timeout-minutes: 240
    steps:
      - name: Clean the workspace
        uses: docker://alpine
        with:
          args: /bin/sh -c "rm -rf /github/workspace/.* || rm -rf /github/workspace/*"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Get Version
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build and push (development)
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ci/Dockerfile
          tags: luxonis/depthai-library:${{github.sha}}-armv8
      - name: Build and push (release)
        if: startsWith(github.ref, 'refs/tags/v') == true
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ci/Dockerfile
          tags: luxonis/depthai-library:${{ steps.vars.outputs.short_ref }}-armv8

  upload:
    needs: [build_amd64, build_armv7, build_armv8]
    name: Combine into a single multi-arch image and upload tags
    runs-on: ubuntu-latest
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Get Version
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build and push (development)
        if: startsWith(github.ref, 'refs/tags/v') != true
        run: |
          docker manifest create \
          luxonis/depthai-library:${{ github.sha}} \
          --amend luxonis/depthai-library:${{ github.sha }}-amd64 \
          --amend luxonis/depthai-library:${{ github.sha }}-armv7 \
          --amend luxonis/depthai-library:${{ github.sha }}-armv8
          # Push
          docker manifest push luxonis/depthai-library:${{ github.sha }}

      - name: Build and push (release)
        if: startsWith(github.ref, 'refs/tags/v') == true
        run: |
          docker manifest create \
          luxonis/depthai-library:${{ steps.vars.outputs.short_ref }} \
          --amend luxonis/depthai-library:${{ steps.vars.outputs.short_ref }}-amd64 \
          --amend luxonis/depthai-library:${{ steps.vars.outputs.short_ref }}-armv7 \
          --amend luxonis/depthai-library:${{ steps.vars.outputs.short_ref }}-armv8
          # Push
          docker manifest push luxonis/depthai-library:${{ steps.vars.outputs.short_ref }}
          docker manifest push luxonis/depthai-library:latest
